name: rustdoc
on:
  push:
   branches:
   - master

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
        components: rust-docs

    - name: Build Documentation
      uses: actions-rs/cargo@v1
      env:
        RUSTDOCFLAGS: "-Z unstable-options --extern-html-root-url snafu=https://docs.rs/snafu/0.7.1/ --extern-html-root-url futures_io=https://docs.rs/futures-io/0.3/"
      with:
        command: doc
        args: -p contec-protocol --no-deps

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true